import { useState } from "react";
import { ArrowRight, CheckCircle2, Globe2, Play, RefreshCw } from "lucide-react";
import { api } from "../api";
import type { ImportPreviewItem, WebsiteImportRecord } from "../types";

const suggested = ["title", "content", "url", "author", "published_at"];
export function ImportWorkspace({ onCreated }: { onCreated: () => void }) {
  const [job, setJob] = useState<WebsiteImportRecord | null>(null); const [items,setItems]=useState<ImportPreviewItem[]>([]); const [url,setUrl]=useState(""); const [description,setDescription]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function run(action: "create"|"probe"|"compile"|"preview"|"confirm") { setBusy(true);setError("");try { if(action==="create"){const host=new URL(url).hostname; setJob(await api.createImport({source_url:url,intent:{description,fields:suggested,item_type:"article"},scope:{follow_details:true,preview_pages:2,allowed_domains:[host]},runtime_preference:"auto"}));} else if(!job) return; else if(action==="probe") setJob(await api.probeImport(job.id)); else if(action==="compile") setJob(await api.compileImport(job.id)); else if(action==="preview") {setItems(await api.previewImport(job.id)); setJob({...job,status:"PREVIEW_READY"});} else {const next=await api.confirmImport(job.id);setJob(next);onCreated();}}catch(e){setError(e instanceof Error?e.message:"请求失败")}finally{setBusy(false)} }
  if (!job) return <section className="data-view import-workspace"><header><div><h1>导入网站</h1><p>受控探测后生成可编辑的流程草稿。</p></div></header><div className="import-form"><label>网站 URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/news" /></label><label>采集目标<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="采集文章标题、正文、作者和发布时间" /></label><p>建议字段：{suggested.join(" · ")}</p><button className="button primary" disabled={busy||!url||!description} onClick={()=>void run("create")}>开始安全探测 <ArrowRight size={15}/></button></div>{error&&<p className="inline-error">{error}</p>}</section>;
  const report=job.probe_report_json as {strategy?:string;confidence?:number;page_kind?:string}|null;
  return <section className="data-view import-workspace"><header><div><h1>网站导入</h1><p><code>{job.status}</code> · {job.source_url}</p></div></header>{error&&<p className="inline-error">{error}</p>}<div className="import-progress"><div><strong>探测</strong><span>{report ? `${report.strategy} / ${report.page_kind} / ${Math.round((report.confidence??0)*100)}%` : "等待开始"}</span></div><div><strong>流程草稿</strong><span>{job.flow_draft_json ? `${job.flow_draft_json.field_bindings?.length??0} 个字段映射` : "尚未生成"}</span></div><div><strong>预览</strong><span>{items.length ? `${items.length} 条隔离记录` : "尚未运行"}</span></div></div>{job.status==="DRAFT"&&<button className="button primary" disabled={busy} onClick={()=>void run("probe")}><Globe2 size={15}/>运行 Probe</button>}{job.status==="PROBE_READY"&&<button className="button primary" disabled={busy} onClick={()=>void run("compile")}>生成流程草稿 <ArrowRight size={15}/></button>}{job.status==="DRAFT_READY"&&<button className="button primary" disabled={busy} onClick={()=>void run("preview")}><Play size={15}/>运行预览</button>}{job.status==="PREVIEW_READY"&&<div className="import-actions"><button className="button" disabled={busy} onClick={()=>void run("preview")}><RefreshCw size={15}/>重新预览</button><button className="button primary" disabled={busy} onClick={()=>void run("confirm")}><CheckCircle2 size={15}/>确认创建流程</button></div>}{job.status==="CREATED"&&<p className="import-created"><CheckCircle2 size={18}/>流程已创建：<code>{job.created_flow_id}</code></p>}{items.length>0&&<div className="table-wrap"><table><thead><tr>{Object.keys(items[0].normalized_json).map(key=><th key={key}>{key}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id}>{Object.values(item.normalized_json).map((value,i)=><td key={i}>{String(value)}</td>)}</tr>)}</tbody></table></div>}</section>;
}
